In [82]:
import numpy as np
import pandas as pd

df_prices=pd.read_csv("../dataset/BTC-Hourly.csv")

df_prices.head()

unix                 date   symbol      open      high       low  \
0  1646092800  2022-03-01 00:00:00  BTC/USD  43221.71  43626.49  43185.48   
1  1646089200  2022-02-28 23:00:00  BTC/USD  43085.30  43364.81  42892.37   
2  1646085600  2022-02-28 22:00:00  BTC/USD  41657.23  44256.08  41650.29   
3  1646082000  2022-02-28 21:00:00  BTC/USD  41917.09  41917.09  41542.60   
4  1646078400  2022-02-28 20:00:00  BTC/USD  41361.99  41971.00  41284.11   

      close  Volume BTC    Volume USD  
0  43312.27   52.056320  2.254677e+06  
1  43178.98  106.816103  4.612210e+06  
2  42907.32  527.540571  2.263535e+07  
3  41659.53   69.751680  2.905822e+06  
4  41914.97  247.151654  1.035935e+07

In [83]:
drop_colums=['unix','symbol']
df_prices.drop(columns=drop_colums, inplace=True)

df_prices.head()

date      open      high       low     close  Volume BTC  \
0  2022-03-01 00:00:00  43221.71  43626.49  43185.48  43312.27   52.056320   
1  2022-02-28 23:00:00  43085.30  43364.81  42892.37  43178.98  106.816103   
2  2022-02-28 22:00:00  41657.23  44256.08  41650.29  42907.32  527.540571   
3  2022-02-28 21:00:00  41917.09  41917.09  41542.60  41659.53   69.751680   
4  2022-02-28 20:00:00  41361.99  41971.00  41284.11  41914.97  247.151654   

     Volume USD  
0  2.254677e+06  
1  4.612210e+06  
2  2.263535e+07  
3  2.905822e+06  
4  1.035935e+07

In [84]:
df_prices['date']=pd.to_datetime(df_prices['date'])

start_time=pd.to_datetime('2021-02-05 10:00:00')
end_time=pd.to_datetime('2021-07-30 23:00:00')

df_prices=df_prices[(df_prices['date'] >= start_time) & (df_prices['date'] <= end_time)]

df_prices = df_prices.reset_index(drop=True)

In [85]:
df_prices = df_prices.sort_values(by='date').reset_index(drop=True)
df_prices


date      open      high       low     close  Volume BTC  \
0    2021-02-05 10:00:00  37297.06  37698.74  37208.60  37449.95  153.306192   
1    2021-02-05 11:00:00  37427.27  37775.89  37427.27  37745.68  101.295697   
2    2021-02-05 12:00:00  37749.62  38168.36  37595.21  37907.00  444.407083   
3    2021-02-05 13:00:00  37885.00  38351.04  37828.22  38333.77  307.770178   
4    2021-02-05 14:00:00  38335.74  38350.26  38020.14  38153.19  439.239904   
...                  ...       ...       ...       ...       ...         ...   
4209 2021-07-30 19:00:00  39136.53  39901.00  39094.76  39901.00  153.993616   
4210 2021-07-30 20:00:00  39909.99  41663.99  39739.00  40691.14  516.378551   
4211 2021-07-30 21:00:00  40721.76  41547.07  40663.47  41246.70  361.135721   
4212 2021-07-30 22:00:00  41213.84  41514.22  41011.42  41384.94  138.238985   
4213 2021-07-30 23:00:00  41456.79  42335.50  41338.82  42234.89  333.115697   

        Volume USD  
0     5.741309e+06  
1     3.823475e+06  
2     1.684614e+07  
3     1.179799e+07  
4     1.675840e+07  
...            ...  
4209  6.144499e+06  
4210  2.101203e+07  
4211  1.489566e+07  
4212  5.721012e+06  
4213  1.406910e+07  

[4214 rows x 7 columns]

In [86]:
df_sentiment=pd.read_csv('../dataset/hourly_avg_sentiment.csv')
df_sentiment

hour  avg_sentiment  sentiment_volatility  tweet_volume  \
0     2021-02-05 10:00:00       0.232025              0.287001            11   
1     2021-02-05 11:00:00       0.119410              0.543480            88   
2     2021-02-05 12:00:00       0.280681              0.535522           139   
3     2021-02-05 13:00:00       0.200531              0.488745           131   
4     2021-02-05 14:00:00       0.235959              0.504811           160   
...                   ...            ...                   ...           ...   
1249  2021-07-30 19:00:00       0.362750              0.544540          1580   
1250  2021-07-30 20:00:00       0.314065              0.545580          2246   
1251  2021-07-30 21:00:00       0.292241              0.544589          2360   
1252  2021-07-30 22:00:00       0.360520              0.568008          1688   
1253  2021-07-30 23:00:00       0.321412              0.551344          1730   

      count_neg  count_neu  count_pos  
0      0.000000   0.727273   0.272727  
1      0.147727   0.556818   0.295455  
2      0.122302   0.460432   0.417266  
3      0.137405   0.534351   0.328244  
4      0.093750   0.537500   0.368750  
...         ...        ...        ...  
1249   0.118354   0.381013   0.500633  
1250   0.121549   0.437667   0.440784  
1251   0.130508   0.438559   0.430932  
1252   0.121445   0.377370   0.501185  
1253   0.138728   0.402890   0.458382  

[1254 rows x 7 columns]

## Filling the missing timestamps in the df_sentiment with 0 and merging both dataframes

In [87]:
import pandas as pd

# Assuming you already did:
df_prices['date'] = pd.to_datetime(df_prices['date'])
df_sentiment['hour'] = pd.to_datetime(df_sentiment['hour'])

df_prices = df_prices.set_index('date')
df_sentiment = df_sentiment.set_index('hour')

# Create the missingness flag BEFORE filling NaNs
missing_flag = df_sentiment.isna().any(axis=1).astype(int)
# This flag is 1 if any column in that row is NaN, else 0

# Reindex sentiment to match price timestamps
df_sentiment = df_sentiment.reindex(df_prices.index)

# Reindex flag as well, align with sentiment index
missing_flag = missing_flag.reindex(df_prices.index).fillna(1).astype(int)  # missing rows get flag=1

# Fill missing sentiment values with 0
df_sentiment = df_sentiment.fillna({
    'avg_sentiment': 0.0,
    'sentiment_volatility': 0.0,
    'tweet_volume': 0,
    'count_neg': 0,
    'count_neu': 0,
    'count_pos': 0
})

# Add missingness flag column to sentiment dataframe
df_sentiment['sentiment_missing_flag'] = missing_flag

# Merge price and sentiment dataframes
df_merged = pd.concat([df_prices, df_sentiment], axis=1).reset_index()

print(df_merged[['date', 'sentiment_missing_flag']].head(1000))


                   date  sentiment_missing_flag
0   2021-02-05 10:00:00                       0
1   2021-02-05 11:00:00                       0
2   2021-02-05 12:00:00                       0
3   2021-02-05 13:00:00                       0
4   2021-02-05 14:00:00                       0
..                  ...                     ...
995 2021-03-18 21:00:00                       1
996 2021-03-18 22:00:00                       1
997 2021-03-18 23:00:00                       1
998 2021-03-19 00:00:00                       1
999 2021-03-19 01:00:00                       1

[1000 rows x 2 columns]


In [88]:
df_merged.head()

date      open      high       low     close  Volume BTC  \
0 2021-02-05 10:00:00  37297.06  37698.74  37208.60  37449.95  153.306192   
1 2021-02-05 11:00:00  37427.27  37775.89  37427.27  37745.68  101.295697   
2 2021-02-05 12:00:00  37749.62  38168.36  37595.21  37907.00  444.407083   
3 2021-02-05 13:00:00  37885.00  38351.04  37828.22  38333.77  307.770178   
4 2021-02-05 14:00:00  38335.74  38350.26  38020.14  38153.19  439.239904   

     Volume USD  avg_sentiment  sentiment_volatility  tweet_volume  count_neg  \
0  5.741309e+06       0.232025              0.287001          11.0   0.000000   
1  3.823475e+06       0.119410              0.543480          88.0   0.147727   
2  1.684614e+07       0.280681              0.535522         139.0   0.122302   
3  1.179799e+07       0.200531              0.488745         131.0   0.137405   
4  1.675840e+07       0.235959              0.504811         160.0   0.093750   

   count_neu  count_pos  sentiment_missing_flag  
0   0.727273   0.272727                       0  
1   0.556818   0.295455                       0  
2   0.460432   0.417266                       0  
3   0.534351   0.328244                       0  
4   0.537500   0.368750                       0

In [89]:
(df_merged['avg_sentiment']==0).sum()

2960

In [90]:
df_merged['returns'] = (df_merged['close'] - df_merged['open']) / df_merged['open']
df_merged['volatility'] = (df_merged['high'] - df_merged['low']) / df_merged['open']
df_merged['momentum_3'] = df_merged['close'] / df_merged['close'].shift(3) - 1
df_merged['rolling_mean_close_3'] = df_merged['close'].rolling(window=3).mean()
df_merged['rolling_std_close_3'] = df_merged['close'].rolling(window=3).std()
df_merged['high_low_ratio'] = df_merged['high'] / df_merged['low']


In [91]:
df_merged['future_return'] = (df_merged['close'].shift(-1) - df_merged['close']) / df_merged['close']

def label_action(x, threshold=0.01):
    if x > threshold:
        return 1  # buy
    elif x < -threshold:
        return 2  # sell
    else:
        return 0  # hold

df_merged['target'] = df_merged['future_return'].apply(label_action)



In [92]:
df_merged['sentiment_diff'] = df_merged['count_pos'] - df_merged['count_neg']
df_merged['sentiment_ratio'] = (df_merged['count_pos'] + 1) / (df_merged['count_neg'] + 1)
df_merged['sentiment_intensity'] = df_merged['avg_sentiment'] * df_merged['tweet_volume']


In [93]:
df_merged['volume_btc_change'] = df_merged['Volume BTC'].pct_change() 
df_merged['volume_usd_change'] = df_merged['Volume USD'].pct_change() 
df_merged['tweet_volume_change'] = df_merged['tweet_volume'].pct_change() 


In [94]:
df_merged.columns


Index(['date', 'open', 'high', 'low', 'close', 'Volume BTC', 'Volume USD',
       'avg_sentiment', 'sentiment_volatility', 'tweet_volume', 'count_neg',
       'count_neu', 'count_pos', 'sentiment_missing_flag', 'returns',
       'volatility', 'momentum_3', 'rolling_mean_close_3',
       'rolling_std_close_3', 'high_low_ratio', 'future_return', 'target',
       'sentiment_diff', 'sentiment_ratio', 'sentiment_intensity',
       'volume_btc_change', 'volume_usd_change', 'tweet_volume_change'],
      dtype='object')

## XGBoost model

In [95]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
import matplotlib.pyplot as plt

features=df_merged.drop(columns=['date','future_return','target'])
target=df_merged['target']



In [96]:
inf_columns = features.columns[np.isinf(features).sum() > 0].tolist()
inf_columns


['tweet_volume_change']

In [97]:
np.isinf(features['tweet_volume_change']).sum()

13

In [98]:
mask = ~np.isinf(features['tweet_volume_change'])
features = features[mask].reset_index(drop=True)
target = target[mask].reset_index(drop=True)

In [99]:
features.fillna(0, inplace=True)
target.fillna(0, inplace=True)

In [100]:
split_index= int(len(df_merged) * 0.8)
X_train = features[:split_index]    
X_test = features[split_index:]
y_train = target[:split_index]
y_test = target[split_index:]

model=XGBClassifier(
    eta=0.1,
    max_depth=6,
    objective='multi:softmax',
    num_class=3,
    eval_metric='mlogloss',
    reg_lambda=2,
    reg_alpha=0.5
)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eta=0.1, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, ...)

In [101]:
predictions= model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)





In [102]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred, target_names=['Hold', 'Buy', 'Sell']))


Accuracy: 0.8204819277108434
Confusion Matrix:
 [[677  33  15]
 [ 53   3   2]
 [ 43   3   1]]
Classification Report:
               precision    recall  f1-score   support

        Hold       0.88      0.93      0.90       725
         Buy       0.08      0.05      0.06        58
        Sell       0.06      0.02      0.03        47

    accuracy                           0.82       830
   macro avg       0.34      0.34      0.33       830
weighted avg       0.77      0.82      0.80       830

